environment:
 #DOC mapr core version (required, must be 5.1.0 and above)
 mapr_core_version: 6.0.1

#DOC attributes for /config api
config:
  #DOC list of hosts we want to install packages on (required)
  #DOC installer host must be one of the hosts in this list
  hosts: [mapr0]

  security: True
  #provider:
  #  id: AZURE
  environment: amazon
  #DOC user id, must be present for every host defined above (required)
  ssh_id: root
  ssh_password: mapr
  #DOC license type (M3 = community edition, M5 = enterprise edition)
  license_type: M5
  #DOC MEP version (required only for Mapr 5.2.0 and above)
  mep_version: 5.0.0
  #DOC list of disks to install packages on (required)
  disks: []
  #DOC disk stripe width (optional)
  #disk_stripe: 3
  #DOC name of the cluster (required)
  cluster_name: mapr600
  #DOC hashmap of services to be installed (optional)
  services:
    template-05-converged:
